FROM node:14.5.0-slim
# Create app directory
COPY --from=thkcodearch/intercom-frontend:latest /usr/share/nginx/html /intercom-frontend/dist
WORKDIR /app
RUN npm install -g @nestjs/cli nodemon
EXPOSE 3000
CMD npm install && npm run start:dev
